### PR TITLE
Extch 348 gatsby upgrade to v5

### PR DESCRIPTION
**Pull request by tnordberg**
The P.R. is the result of migrating app-template from Gatsby v4 to v5, and accounting for all the other necessary upgrades. 

Important notes:
1. You need to be using Node v18
2. The new GraphQL engine has slightly changed the way they handle sort and aggregation fields (see example here: https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#graphql-schema-changes-to-sort-and-aggregation-fields)
3. The built-in GraphiQL tool has a new cool interface 

To test
- Pull down this branch
- Set node version to 18
- Run `yarn` to install packages
- Run `yarn develop` and confirm base application is working
- Run `yarn install:contentful` and follow prompts to connect with existing Contentful Space/Content Type
- Run `yarn develop` and check that pages are being rendered based on the content type you selected
- Run `yarn install:arduino-base` to install the arduino-base submodel
- Run `yarn develop` and check that the [test page](https://d.pr/i/PLfKRq) is rendered (http://localhost:3000/arduino/)
- (Optional) If you have an arduino, connect and relaunch app to test communication

### Preparation checklist

* [x] Merge `main` into your branch and resolve resulting conflicts
* [x] Select one or multiple reviewers who are well suited to discuss your changes
* [ ] Write a new programmatic test, if warranted
* [ ] Edit or create the documentation necessary for others to make use of your changes

### Writing a helpful description

* [x] Link to the specific user-story being addressed, and describe how you've addressed it
* [x] Describe how your changes should be tested
* [ ] Link to specific files, line-numbers, and decisions you would like feedback on
* [ ] Bonus: Include screenshots or screen-captures to describe any visual changes

### CODE REVIEW

**Comment by calym** [comment]
I successfully got the base app working, but `yarn develop` after `yarn install:contentful` got me this error: 
Screenshot 2023-09-12 at 10 58 17 AM

I tried it both with a flipbook and a videoSelector. If you can't reproduce it, lmk if you want to take a look together. (It's very possible something isn't configured in my new dev environment.)

**Comment by tnordberg** [comment]
> I successfully got the base app working, but `yarn develop` after `yarn install:contentful` got me this error: Screenshot 2023-09-12 at 10 58 17 AM
> 
> I tried it both with a flipbook and a videoSelector. If you can't reproduce it, lmk if you want to take a look together. (It's very possible something isn't configured in my new dev environment.)


Thanks for catching this @calym – I tried starting fresh and could still build after the contentful install step, so I suspect something differs about our setups—good fodder for our work session this week. 

I'm not immediately familiar with your error and it is especially strange that it happened _after_ the contentful step.

In the meantime, could you check that your command line tools for xcode have been installed/updated? 

Also, run this command to see if we differ:
`clang --version`

Here's me output:
```
Apple clang version 13.0.0 (clang-1300.0.27.3)
Target: arm64-apple-darwin21.4.0
Thread model: posix
```

**Comment by calym** [comment]
Hmm. Here's mine:
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.6.0
Thread model: posix

**Review by calym — APPROVED** [review]
Working on an M2 with Arduino/Stele! LGTM

**Pull request merged**
